[versions]
agp = "8.9.2"
kotlin = "2.0.21"
coreKtx = "1.15.0"
media = "1.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
